# apiVersion: v1
# kind: Service
# metadata:
#   name: traefik-service
#   namespace: hyperion
#   labels:
#     app: ingress
# spec:
#   ports:
#     - port: 80
#   selector:
#     app: whoami

apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: hyperion
  labels:
    app: whoami
spec:
  ports:
    - port: 80
  selector:
    app: whoami