apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: hyperion
data:
  ENVIRONMENT: "staging"
  PG_HOST: "postgres-postgresql.hyperion.svc.cluster.local"
  PG_DB: "hyperion"
  PG_USER: "postgres"
  PG_PORT: "5432"
  REDIS_HOST: "redis-master.hyperion.svc.cluster.local"
  ALGORITHM: "HS256"
