apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: hyperion
  labels:
    app: api
spec:
  containers:
  - name: hyperion
    image: docker.io/williamle92/hyperion:latest
    ports:
    - containerPort: 8000
