# kubernetes/hyperion/templates/ingress-standalone.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hyperion-ingress
  namespace: hyperion
spec:
  entryPoints:
    - web
  routes:
    # Traefik Dashboard UI
    - match: PathPrefix(`/dashboard`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
    # Traefik Dashboard API (needed for dashboard to fetch data)
    - match: PathPrefix(`/api`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
    # Your Hyperion API
    - match: PathPrefix(`/v1/api`)
      kind: Rule
      services:
        - name: hyperion
          port: 8000
