# kubernetes/hyperion/templates/ingress-standalone.yaml
{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: hyperion-ingress
  namespace: hyperion
spec:
  entryPoints:
    - web
    - websecure
  tls:
    secretName: hyperion-tls
  routes:
    # Traefik Dashboard UI
    - match: Host(`hyperion.local`) && PathPrefix(`/dashboard`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
    # Traefik Dashboard API (needed for dashboard to fetch data)
    - match: Host(`hyperion.local`) && PathPrefix(`/api`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
    # Your Hyperion API
    - match: Host(`hyperion.local`) && PathPrefix(`/v1/api`)
      kind: Rule
      services:
        - name: hyperion
          port: 8000
{{- end -}}
