apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hyperion.fullname" . }}-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hyperion.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  {{- if .Values.worker }}
  {{- if not .Values.worker.autoscaling.enabled }}
  replicas: {{ .Values.worker.replicaCount }}
  {{- end }}
  {{- else }}
  replicas: 2
  {{- end }}
  selector:
    matchLabels:
      {{- include "hyperion.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "hyperion.labels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.serviceAccount }}
      serviceAccountName: {{ include "hyperion.serviceAccountName" $ }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: worker
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["celery"]
        args:
          - "-A"
          - "api.backend.worker.tasks"
          - "worker"
          - "--loglevel=info"
        envFrom:
          {{- toYaml .Values.envFrom | nindent 10 }}
        resources:
          {{- toYaml .Values.worker.resources | nindent 10 }}
